# Site settings
title: Gewürzinsel der Karibik
client:
  name: Grenada
  link: "http://bit.ly/2HSy3cC"
  link2: "http://bit.ly/2ShX45Y"

core-se-link: https://www.secretescapes.de/aktuelle-angebote?utm_source=SE&utm_medium=hub&utm_campaign=grenada-2019_DE_2019
se-tracking-link: "?utm_source=SE&utm_medium=hub&utm_campaign=grenada-2019_DE_2019"
description: >
  Erkunden Sie Ihren Geschmackssinn auf der Gewürzinsel Grenada und erfüllen sich Ihren Traumurlaub in der Karibik.
# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/grenada-2019" # the subpath of your site, e.g. /blog/
img:     "/de/grenada-2019/_assets/img"
css:     "/de/grenada-2019/_assets/css"
js:      "/de/grenada-2019/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
